api_url: "http://localhost:8000/general/v0/general" 
api_key: "${UNSTRUCTURED_API_KEY}"
strategy: "hi_res"
hi_res_model_name: "yolox"
ocr_languages: []
languages: []
coordinates: false
skip_infer_table_types: []
encoding: "utf-8"
xml_keep_tags: false
include_page_breaks: false
unique_element_ids: false
chunking_strategy: "by_title"
chunking_params: {}
parallel_mode_enabled: false
parallel_mode_url: null
parallel_mode_threads: 3
parallel_mode_split_size: 1
parallel_retry_attempts: 2