processor:
  reprocess: False
  verbose: True
  work_dir: 'work'
  output_dir: 'output'
  num_processes: 2
  raise_on_error: False

read:
  download_dir: 'downloads'
  re_download: False
  preserve_downloads: False
  download_only: False
  max_docs: 100

partitioning:
  pdf_infer_table_structure: False
  skip_infer_table_types: []
  strategy: 'hi_res'
  ocr_languages: ['eng']
  encoding: 'utf-8'
  fields_include: ['element_id', 'text', 'type', 'metadata', 'embeddings']
  flatten_metadata: False
  metadata_exclude: []
  metadata_include: []
  partition_endpoint: 'http://localhost:8000/general/v0/general'
  partition_by_api: True

sources:
  local:
    recursive: True
  confluence:
    api_token: 'your_confluence_api_token'
    user_email: 'your_email@example.com'
    url: 'https://your-confluence-url.atlassian.net'
  github:
    url: 'owner/repo'
    branch: 'main'
  google_drive:
    service_account_key: 'path/to/service_account_key.json'
    recursive: True
    drive_id: 'your_drive_id'

chunking:
  enabled: True
  strategy: 'basic'
  chunk_max_characters: 1500
  chunk_overlap: 300

embedding:
  enabled: True
  provider: 'langchain-huggingface'
  api_key_env_var: 'OPENAI_API_KEY'
  model_name: 'intfloat/e5-large-v2'

destination_connectors:
  enabled: True
  type: 'chroma'
  batch_size: 80
  chroma:
    host: 'localhost'
    port: 8002
    collection_name: 'samba_parse_test'
    tenant: 'default_tenant'
    database: 'default_database'
  qdrant:
    location: 'http://localhost:6333'
    collection_name: 'test'

    