api: "sambastudio"

embedding_model: "sambastudio"

llm: 
    "temperature": 0.0
    "max_tokens_to_generate": 1200
    "sambaverse_model_name": "Meta/llama-2-70b-chat-hf"
    "sambaverse_select_expert": "llama-2-70b-chat-hf"

lvlm:
    "do_sample": false
    "max_tokens_to_generate": 512 
    "temperature": 1
    "top_k": 50
    "top_p": 1

retrieval:
    "max_characters": 800
    "new_after_n_chars": 500
    "combine_text_under_n_chars": 300
    "k_retrieved_documents": 4

