
    
api: sambastudio

llm: 
    "temperature": 0.1
    "max_tokens_to_generate": 1024
    "sambaverse_model_name": "Mistral/Mistral-7B-Instruct-v0.2"
    "samabaverse_select_expert": "Mistral-7B-Instruct-v0.2"
    "coe_routing": true

retrieval:
    "chunk_size": 1000
    "chunk_overlap": 200
    "db_type": "faiss"