eval_llm:  
  sambaverse_model_name: "Mistral/Mistral-7B-Instruct-v0.2"
  model_kwargs:
    do_sample: false 
    temperature: 0.01
    max_tokens_to_generate: 512
    select_expert: "Mistral-7B-Instruct-v0.2"
    process_prompt: True
    
evaluation:
  data_path: "../../data/eval/datasets/adi_qna_sample/eval_set_midsize.csv"  
  num_samples: 30
  log_wandb: false