eval_dataset:
  path: eval_set.csv
  # hf_dataset_name: squad_v2
  question_col: question
  answer_col: ground_truth
  context_col: context

llms:
  - name: llm1
    model_kwargs:
      temperature: 0.5
      max_tokens: 1000

  # - name: llm2
  #   model_kwargs:
  #     temperature: 0.3
  #     max_tokens: 200

  # - name: llm3
  #   model_kwargs:
  #     temperature: 0.7
  #     max_tokens: 150

eval_llms:
  - name: eval_llm1
    model_kwargs:
      temperature: 0.4
      max_tokens: 1000

  # - name: eval_llm2
  #   model_kwargs:
  #     temperature: 0.6
  #     max_tokens: 200

  # - name: eval_llm3
  #   model_kwargs:
  #     temperature: 0.8
  #     max_tokens: 150

vector_db:
  location: adi_vdb.chromadb

embeddings:
  model_name: hkunlp/instructor-large

evaluation:
  num_samples: 100
  log_wandb: true
  project_name: rag-pipeline-eval
  eval_name: test-run-1
  methodology: rag_pipeline

pipeline:
  class: rag_pipeline.RAGPipeline
  kwargs:
    vector_db_location: adi_vdb.chromadb